[package]
name = "dxf2image"
version = "0.1.0"
authors = ["Kohei Fujino <appleblueberrycherry@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
dxf = { git = "https://github.com/ixmilia/dxf-rs", branch = "main" }
svg = { path = "./svg" }
bitmap = { path = "./bitmap", optional = true }

[features]
default = []
png = ["bitmap"]
